repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use latest stable version
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9  # Use latest stable version
    hooks:
      - id: ruff
        args: [--fix]  # Auto-fix linting issues

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use latest stable version
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
